wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722443742
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
LR_plateau_patience:
  desc: null
  value: 39
batch_size:
  desc: null
  value: 13
beta_1:
  desc: null
  value: 1.57834453133631
beta_2:
  desc: null
  value: 0.6587512090548565
dropout_1:
  desc: null
  value: 0.3633269726596447
dropout_2:
  desc: null
  value: 0.3959677605897396
dropout_3:
  desc: null
  value: 0.3856017528300489
early_stopping_patience:
  desc: null
  value: 11
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0016480694277980254
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 79
reduce_LR_factor:
  desc: null
  value: 0.49203761510006305
reduce_LR_minLR:
  desc: null
  value: 1.5141563541750594e-06
train_data_version:
  desc: null
  value: ZTFSS
