wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722439247
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 7
      - 19
      - 23
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
image_size:
  desc: null
  value:
  - 63
  - 63
  - 3
metadata_size:
  desc: null
  value:
  - 14
dropout_1:
  desc: null
  value: 0.3
dropout_2:
  desc: null
  value: 0.3
dropout_3:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 42
train_data_version:
  desc: null
  value: ZTFSS
early_stopping_patience:
  desc: null
  value: 10
LR_plateau_patience:
  desc: null
  value: 20
reduce_LR_factor:
  desc: null
  value: 0.5
reduce_LR_minLR:
  desc: null
  value: 1.0e-06
beta_1:
  desc: null
  value: 0.9
beta_2:
  desc: null
  value: 0.999
metadata_cols:
  desc: null
  value:
  - sgscore1
  - distpsnr1
  - sgscore2
  - distpsnr2
  - fwhm
  - magpsf
  - sigmapsf
  - ra
  - dec
  - diffmaglim
  - ndethist
  - nmtchps
  - age
  - peakmag_so_far
