wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722443724
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
LR_plateau_patience:
  desc: null
  value: 14
batch_size:
  desc: null
  value: 13
beta_1:
  desc: null
  value: 1.562692806798274
beta_2:
  desc: null
  value: 1.5231075014445092
dropout_1:
  desc: null
  value: 0.390871151633445
dropout_2:
  desc: null
  value: 0.4100537466864169
dropout_3:
  desc: null
  value: 0.40038635912078346
early_stopping_patience:
  desc: null
  value: 20
epochs:
  desc: null
  value: 15
learning_rate:
  desc: null
  value: 0.0014634278437676296
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 56
reduce_LR_factor:
  desc: null
  value: 0.3992669561664373
reduce_LR_minLR:
  desc: null
  value: 9.248771596202132e-07
train_data_version:
  desc: null
  value: ZTFSS
