wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722444644
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
LR_plateau_patience:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 7
beta_1:
  desc: null
  value: 1.7923124806266546
beta_2:
  desc: null
  value: 1.4542467924559934
dropout_1:
  desc: null
  value: 0.16062120583706038
dropout_2:
  desc: null
  value: 0.35597717193089484
dropout_3:
  desc: null
  value: 0.19053589368831675
early_stopping_patience:
  desc: null
  value: 13
epochs:
  desc: null
  value: 19
learning_rate:
  desc: null
  value: 0.0017148222319933032
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 43
reduce_LR_factor:
  desc: null
  value: 0.9537785812480692
reduce_LR_minLR:
  desc: null
  value: 1.1135979121634183e-06
train_data_version:
  desc: null
  value: ZTFSS
