wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722444614
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
LR_plateau_patience:
  desc: null
  value: 32
batch_size:
  desc: null
  value: 12
beta_1:
  desc: null
  value: 1.3036537144810787
beta_2:
  desc: null
  value: 1.5792971542600325
dropout_1:
  desc: null
  value: 0.4999509954279079
dropout_2:
  desc: null
  value: 0.4496545907700007
dropout_3:
  desc: null
  value: 0.46504358982157445
early_stopping_patience:
  desc: null
  value: 11
epochs:
  desc: null
  value: 8
learning_rate:
  desc: null
  value: 0.0006020105791137936
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 59
reduce_LR_factor:
  desc: null
  value: 0.9230805937994744
reduce_LR_minLR:
  desc: null
  value: 6.474655636419928e-07
train_data_version:
  desc: null
  value: ZTFSS
