wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722444689
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
LR_plateau_patience:
  desc: null
  value: 38
batch_size:
  desc: null
  value: 5
beta_1:
  desc: null
  value: 1.3678044411124932
beta_2:
  desc: null
  value: 0.9423899333193332
dropout_1:
  desc: null
  value: 0.16371582760026393
dropout_2:
  desc: null
  value: 0.4566540101381577
dropout_3:
  desc: null
  value: 0.1985710115137745
early_stopping_patience:
  desc: null
  value: 8
epochs:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0010345279113016304
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 25
reduce_LR_factor:
  desc: null
  value: 0.90254582602002
reduce_LR_minLR:
  desc: null
  value: 5.248055711904084e-07
train_data_version:
  desc: null
  value: ZTFSS
