wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.17.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1722443710
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      4: 3.11.4
      5: 0.17.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: batch/batch_step
      6:
      - 3
LR_plateau_patience:
  desc: null
  value: 22
batch_size:
  desc: null
  value: 13
beta_1:
  desc: null
  value: 0.4501544060034156
beta_2:
  desc: null
  value: 0.952545360088812
dropout_1:
  desc: null
  value: 0.21604015086770084
dropout_2:
  desc: null
  value: 0.191552367645959
dropout_3:
  desc: null
  value: 0.2338170951199519
early_stopping_patience:
  desc: null
  value: 10
epochs:
  desc: null
  value: 11
learning_rate:
  desc: null
  value: 0.0013082251010050356
loss:
  desc: null
  value: binary_crossentropy
optimizer:
  desc: null
  value: adam
random_seed:
  desc: null
  value: 34
reduce_LR_factor:
  desc: null
  value: 0.9085880772932092
reduce_LR_minLR:
  desc: null
  value: 5.410813897968893e-07
train_data_version:
  desc: null
  value: ZTFSS
